### ISSUE TITLE
bar applets not shown

### ISSUE THREAD

**Issue by 0x64746b** [sunaku/wmiirc#34]
```
display:
  [...]
  status:
    - volume:
    - clock:
```

No problems are indicated in `wmiirc.log`:

```
I, [2012-01-09T10:18:39.547018 #17072]  INFO -- : reload
I, [2012-01-09T10:18:39.548205 #17072]  INFO -- : stop
I, [2012-01-09T10:18:39.637789 #17135]  INFO -- : start
```
