### ISSUE TITLE
Moving from TOPLEVEL_BINDING to Button#instance_eval in commit 71bb5a57668ac54c00866c8857e36f2daea09c27 doesn't work

### ISSUE THREAD

**Issue by nougad** [sunaku/wmiirc#4]
Minimal setup:

```
display:
  status:
    - test:
      click: status 'test'
```

Fails with "wrong number of arguments (1 for 0) (ArgumentError)" because it wants to call Button(Thread)#status not status on TOPLEVEL_BINDING.

If you using status_click instead of status for example the method is found correctly but all instance-variables are nil because they are only defined in TOPLEVEL_BINDING not in Button-scope.
