### ISSUE TITLE
Caching complete config in one file

### ISSUE THREAD

**Issue by nougad** [sunaku/wmiirc#9]
I thought a little bit about using yaml-references in config file. e.g.:

```
display:
  status:
    wlan0:
      label: &geninit
         .. display status of init script ...
      path: /etc/init.d/net.wlan0
    eth0:
      label: *geninit
      path: /etc/init.d/net.wlan0
```

But this would make it necessary to load complete config at once. Perhaps it would be a nice Idea to cache the complete config in an special file and only diff the timestamps of both files. If config is newer rebuild cache and load it else load only cache.

I tested the cofnig with references and it works pretty well if whole config is in one file of course.

Caching the config is a little bit ugly (I think the performance improvement will be minimal) but perhaps references can make some pretty things possible. What do you think?
